### ISSUE TITLE
apostrophe shown as html tag in the title

### ISSUE THREAD

**Issue by nobanzai** [phpbg/muspnp#4]
If a song or playlist contains an apostrophe in its name, it is shown as "&apos;" in the title.
In the list it is shown correctly as '.

**Comment by phpbg** [comment]
Can you be more specific where the double quotes appear?

I tried on kodi renderer, and the label is fine on kodi, and on muspnp list too.

**Comment by nobanzai** [comment]
No double quotes - sorry. This is an apostrophe between double quotes.
![Screenshot_20220405_122140](https://user-images.githubusercontent.com/10534549/161733833-62498cfb-6255-469e-967e-ce5f64db06e5.jpg)
See the \&apos; in the title? It should be Michael's.

**Comment by phpbg** [comment]
OK I see.

I also see weird things below in the playlist: you should see a proper `<Artist> - <Album>` below song name

I guess it depends on how the server encode things, because I don't reproduce it on ReadyMedia.

Could you please collect a log? See [here](https://github.com/phpbg/muspnp#debug--logs) for some help. If it is unclear feel free to ask.

**Comment by nobanzai** [comment]
Here we go.
[muspnp.log](https://github.com/phpbg/muspnp/files/8440926/muspnp.log)

**Comment by phpbg** [comment]
It should all be fixed in the latest release.

[download 1.1.1 release for windows](https://github.com/phpbg/muspnp/releases/download/1.1.1/muspnp-1.1.1.Setup.exe)

Can you try it and post back a screenshot at the same location?

**Comment by nobanzai** [comment]
As I wrote, I don't use Windows, but Linux (openSUSE Tumbleweed).
I downloaded and installed your new version. Now it looks perfect:

![image](https://user-images.githubusercontent.com/10534549/162623981-bb267eb3-c27c-4d50-ba95-38e798024f83.png)

Thx a lot!
